#include "menus/menu_hundo_saves/include/hundo_saves_menu.h"
#include "gz_flags.h"
#include "save_specials.h"
#include "save_manager.h"
#include "rels/include/defines.h"
#include "menus/utils/menu_mgr.h"

KEEP_FUNC HundoSavesMenu::HundoSavesMenu(Cursor& cursor)
    : Menu(cursor),
      lines{
          {"mailgame", MAILGAME_HUNDO, "about to start mail minigame for note to mom"},
          {"dragon roost cavern", DRC_INSIDE_HUNDO, "at the beginning of drc"},
          {"pot push storage", POTPUSH_STORAGE_HUNDO, "about to get chest storage in drc"},
          {"boko room", BOKOS_DRC_HUNDO, "inside 3 bokos room"},
          {"drc miniboss", DRC_MINIBOSS_HUNDO, "outside ship, before barrel launch cutscene"},
          {"drc boss key skip", DRC_BK_SKIP_HUNDO, "skip drc boss key with chest storage"},
          {"zephos skip", ZEPHOS_SKIP_HUNDO, "about to skip zephos cutscene"},
          {"dri to windfall swim", DRI_TO_WINDFALL_SWIM_HUNDO, "after zephos skip, about to swim to windfall"},
          {"forest haven swim 1", WINDFALL_TO_FH_HUNDO, "at windfall, about to swim to forest haven"},
          {"deku tree cutscene skip", DTCS_HUNDO, "inside fh, about to perform dtcs"},
          {"leaf to forest of fairies", LEAF_TO_FOF_HUNDO, "at outset island, about to leaf to fof"},
          {"fof fairy clip", FOF_FAIRY_CLIP_HUNDO, "about to roll clip inside fof great fairy"},
          {"leaf to invisible pirate ship", LEAF_TO_SHIP_HUNDO, "at outset, about to leaf to pirate ship"},
          {"ropes 1", ROPES_1_HUNDO, "inside pirate ship, for spoils bag"},
          {"ff1 door teleport", FF1_DOOR_TELEPORT_HUNDO, "on pirate ship at ff1, about to store ship door"},
          {"ropes 2", ROPES_2_HUNDO, "inside pirate ship, for bombs"},
          {"ff1", COMPLETE_FF1_HUNDO, "at the bottom of ff1"},
          {"windfall 1", WINDFALL_1_HUNDO, "1st trip to windfall, about to start hide and seek"},
          {"forest haven swim 2", FH_SWIM_AFTER_WF1_HUNDO, "at windfall docks, about to swim to fh"},
          {"enter forbidden woods", ENTER_FW_HUNDO, "inside forest haven, about to leaf to fw"},
          {"forbidden woods", FW_HUNDO, "start of forbidden woods"},
          {"fw small key skip", FW_SKS_HUNDO, "start of forbidden woods"},
          {"fw miniboss", FW_MINIBOSS_HUNDO, "in fw miniboss room about to fight flying mothula for boomerang"},
          {"fw basement", FW_BASEMENT_HUNDO, "in fw basement for chart chest"},
          {"fw bk skip", FW_BKS_HUNDO, "in double mothula room, for chest storage bk skip"},
          {"kalle demos", FW_BOSS_HUNDO, "forbidden woods boss"},
          {"placing pearls", FH_TO_ETI_SWIM_HUNDO, "at forest haven, about to swim to eastern triangle"},
          {"northern triangle swim", ETI_TO_NTI_SWIM_HUNDO, "at eastern triangle, about to swim to northern triangle"},
          {"islet of steel swim", NTI_TO_IOS_SWIM_HUNDO, "at northern triangle, about to swim to islet of steel"},
          {"outset swim", GF_TO_OUTSET_SWIM_HUNDO, "at greatfish isle, about to swim to outset island"},
          {"outset bomb ledge clip", OUTSET_LEDGE_CLIP_HUNDO, "bomb ledge clip to enter jabun's cave"},
          {"southern triangle swim", OUTSET_TO_STI_HUNDO, "at outset, about to swim to southern triangle"},
          {"tower of the gods", TOTG_START_HUNDO, "start of tower of the gods"},
          {"totg 2nd statue", TOTG_2ND_STATUE_HUNDO, "in 2nd statue room"},
          {"totg miniboss", TOTG_MINIBOSS_HUNDO, "tower of the gods darknut miniboss fight"},
          {"totg scales room", TOTG_SCALES_HUNDO, "in totg scales room before small key"},
          {"gohdan", TOTG_BOSS_HUNDO, "tower of the gods boss"},
          {"cyclos", CYCLOS_HUNDO, "about to fight cyclos for ballad of gales"},
          {"crescent moon swim", NTI_TO_CRESCENT_HUNDO, "at nti, about to swim to crescent moon sub"},
          {"crescent moon submarine", CRESCENT_SUB_HUNDO, "inside crescent moon submarine"},
          {"ff2 swim", CRESCENT_TO_FF2_HUNDO, "double storage superswim from crescent moon"},
          {"helmaroc skip", HELMAROC_SKIP_HUNDO, "skip helmaroc to watch hyrule 2 cutscenes"},
          {"puzzle skip", PUZZLE_SKIP_HUNDO, "in hyrule, before tetra to zelda cutscenes"},
          {"barrier skip", BARRIER_SKIP_HUNDO, "outside hyrule castle, for barrier skip"},
          {"trials skip", TRIALS_SKIP_HUNDO, "in trials hub room, inside ganon\'s tower"},
          {"helmaroc cutscene skip", HELMAROC_CS_SKIP_HUNDO, "about to skip helmaroc cutscene to prevent a crash"},
          {"helmaroc", HELMAROC_FIGHT_HUNDO, "about to fight helmaroc"},
          {"windfall 2", WINDFALL_2_HUNDO, "2nd trip to windfall"},
          {"gale island swim 1", WINDFALL_TO_GALE_SWIM_1_HUNDO, "at windfall, about to swim to gale island for WGA"},
          {"fire mountain swim", GALE_TO_FM_SWIM_HUNDO,
           "at gale island, about to swim to fire mountain for power bracelets"},
          {"bird's peak rock swim", FM_TO_BPR_SWIM_HUNDO,
           "at fire mountain, about to swim to bird's peak rock for triforce chart 3"},
          {"ice ring swim", BPR_TO_ICERING_SWIM_HUNDO,
           "at bird's peak rock, about to swim to ice ring for iron boots and treasure chart 36"},
          {"two eye swim", ICERING_TO_2EYE_SWIM_HUNDO,
           "at ice ring isle, about to swim to two eye reef for double magic octo"},
          {"two eye big octo", TWO_EYE_OCTO_HUNDO, "at two eye, about to fight double magic big octo"},
          {"early earth temple", EARLY_EARTH_TEMPLE_HUNDO, "bomb push clip to enter earth temple"},
          {"earth temple", EARTH_TEMPLE_START_HUNDO, "start of earth temple"},
          {"earth temple chu room", ET_CHUS_ROOM_HUNDO, "earth temple third room"},
          {"song stone skip", ET_SONG_STONE_SKIP_HUNDO, "in basement, about to skip 1st song stone"},
          {"earth temple floormasters", ET_FLOORMASTERS_HUNDO, "in floormaster's room, for treasure chart 20"},
          {"earth temple mirror room", ET_MIRROR_ROOM_HUNDO, "in many mirrors room, about to clip in 3 stalfos room"},
          {"earth temple boss key skip", ET_BKS_HUNDO, "leaf pump to boss door"},
          {"jalhalla", ET_BOSS_HUNDO, "earth temple boss"},
          {"horseshoe swim", HEADSTONE_TO_HORSESHOE_SWIM_HUNDO,
           "at headstone island, about to swim to horseshoe for treasure chart 8"},
          {"play golf", HORSESHOE_GOLF_HUNDO, "golf holes 1 and 2 skip"},
          {"horseshoe chest storage", HORSESHOE_CHEST_STORAGE_HUNDO, "store heart piece chest to enter diamond steppe"},
          {"inside diamond steppe", EARLY_DIAMOND_STEPPE_HUNDO, "inside diamond steppe island for ghost ship chart"},
          {"three eye swim", DSI_TO_3EYE_SWIM_HUNDO,
           "at diamond steppe, about to swim to three eye reef for chart 32 and heart piece"},
          {"forest water shark island swim", FOREST_WATER_SHARK_ISLAND_HUNDO, "start of the forest water segment"},
          {"forest water needle rock swim", FOREST_WATER_NEEDLE_HUNDO,
           "at shark isle, about to swim to needle rock for chart 16"},
          {"five eye swim", NEEDLE_TO_5EYE_SWIM_HUNDO,
           "at needle rock isle, about to swim to five eye reef for chart 41"},
          {"five eye", FIVE_EYE_HUNDO, "clear 5 eye reef for chart 41"},
          {"eastern fairy swim", FIVE_EYE_TO_ETI_SWIM_HUNDO,
           "at five eye, about to swim to eastern fairy island for bomb upgrade and chart 40"},
          {"gale island swim 2", WINDFALL_TO_GALE_SWIM_2_HUNDO,
           "at windfall, about to swim to gale island with double storage"},
          {"wind temple", WIND_TEMPLE_ENTRANCE_HUNDO, "start of wind temple"},
          {"wind temple miniboss", WIND_TEMPLE_MINIBOSS_HUNDO, "wind temple miniboss room"},
          {"wind temple spiky room", WIND_TEMPLE_SPIKY_ROOM_HUNDO, "break floors for chest"},
          {"wind temple locked room", WIND_TEMPLE_LOCKED_ROOM_HUNDO, "big circular room"},
          {"molgera", WT_BOSS_HUNDO, "wind temple boss"},
          {"star island swim", GALE_TO_STAR_SWIM_HUNDO, "at gale island, about to swim to star island"},
          {"star island cave", STAR_CAVE_HUNDO, "inside star island cave for heart piece"},
          {"northern fairy swim", STAR_TO_NFI_HUNDO,
           "at star island, about to swim to northern fairy island for chart 22"},
          {"ghost ship", GHOST_SHIP_HUNDO, "farm rupees inside ghost ship"},
          {"spectacle island minigame", SPECTACLE_HUNDO, "spectacle island minigame for heart piece and chart 17"},
          {"tingle island big octo", TINGLE_OCTO_HUNDO, "about to fight tingle island octo for heart piece"},
          {"stonewatcher swim", TINGLE_TO_STONEWATCHER_SWIM_HUNDO,
           "at tingle island, about to swim to stonewatcher for triforce chart 7"},
          {"stonewatcher cave", STONEWATCHER_CAVE_HUNDO, "inside stonewatcher cave"},
          {"six eye swim", STONEWATCHER_TO_6EYE_SWIM_HUNDO, "swim to six eye reef from stonewatcher lookout platform"},
          {"six eye submarine", SIX_EYE_SUBMARINE_HUNDO, "inside six eye reef submarine"},
          {"cyclops reef", CYCLOPS_REEF_HUNDO, "clear cyclops reef for chart 21"},
          {"pawprint swim", CYCLOPS_TO_PAWPRINT_SWIM_HUNDO,
           "at cyclops reef, about to swim to pawprint island for heart piece"},
          {"overlook swim", PAWPRINT_TO_OVERLOOK_SWIM_HUNDO,
           "at pawprint, about to swim to overlook island for triforce chart 9"},
          {"overlook cave", OVERLOOK_CAVE_HUNDO, "inside overlook island cave"},
          {"savage labyrinth", SAVAGE_LABYRINTH_HUNDO, "start of savage labyrinth"},
          {"savage 10", SAVAGE_10_HUNDO, "savage labyrinth 10th floor"},
          {"savage 20", SAVAGE_20_HUNDO, "savage labyrinth 20th floor"},
          {"savage chest", SAVAGE_CHEST_HUNDO, "farm rupees before getting triforce chart 6"},
          {"orca 500", ORCA500_HUNDO, "hit an old man 500 times"},
          {"pig yeet", PIG_YEET_HUNDO, "pig yeeeeet"},
          {"headstone sub swim", HEADSTONE_SUB_HUNDO,
           "at outset island, about to swim to headstone submarine for chart 14"},
          {"angular swim", ANGULAR_HUNDO, "at headstone, about to swim to angular isles for heart piece"},
          {"bomb island sub swim", BOMB_ISLAND_SUB_HUNDO,
           "at angular, about to swim to bomb island submarine for bottle 3"},
          {"bomb island cave", BOMB_ISLAND_CAVE_HUNDO, "inside bomb island cave"},
          {"fcp swim", FCP_SWIM_HUNDO, "at bomb island, about to swim to flight control platform for heart piece"},
          {"mother and child swim 1", MOTHER_AND_CHILD_SWIM_1_HUNDO,
           "at windfall island, about to swim to mother and child isles"},
          {"four eye swim", FOUR_EYE_SWIM_HUNDO, "at mother and child, about to swim to four eye reef for chart 19"},
          {"western fairy swim", WESTERN_FAIRY_SWIM_HUNDO,
           "at four eye, about to swim to western fairy island for quiver uppgrade"},
          {"rock spire swim", ROCK_SPIRE_SWIM_HUNDO, "peg storage on western fairy island"},
          {"rock spire cave", ROCK_SPIRE_CAVE_HUNDO, "inside rock spire cave"},
          {"forest haven hp on isle fw2", FOREST_HAVEN_HP_CHEST_HUNDO,
           "start of the forest water 2 segment, about to get small island heart piece"},
          {"cabana swim fw2", CABANA_SWIM_HUNDO,
           "at forest haven, about to swim to private oasis for chart 27 and triforce chart 2"},
          {"inside cabana fw2", CABANA_HUNDO, "inside cabana for triforce chart 2"},
          {"tingle island swim fw2", TINGLE_SWIM_HUNDO, "at private oasis, about to swim (or warp) to tingle island"},
          {"gale island swim 3 fw2", GALE_SWIM_3_HUNDO, "at tingle island, about to swim to gale island for shard 2"},
          {"seven star octo fw2", SEVEN_STAR_HUNDO, "seven star isles for heart piece and shard 7"},
          {"two eye swim 2 fw2", TWO_EYE_SWIM_2_HUNDO,
           "at southern triangle, about to swim to 2 eye reef for shard 8 and chart 13"},
          {"two eye reef fw2", TWO_EYE_HUNDO, "clear two eye reef"},
          {"five star swim fw2", FIVE_STAR_SWIM_HUNDO,
           "at two eye, about to swim to five star submarine for heart piece"},
          {"five star chest storage fw2", FIVE_STAR_RAFT_CHEST_HUNDO, "get storage on top of five star submarine"},
          {"thorned fairy swim fw2", THORNED_FAIRY_SWIM_HUNDO, "superswim to thorned fairy from cliff plateau isles"},
          {"mother and child swim 2 fw2", MOTHER_AND_CHILD_SWIM_2_HUNDO,
           "trade postman statue with goron at mother and child isles, end of the forest water 2 segment"},
          {"six eye reef", SIX_EYE_CHART_HUNDO, "clear 6 eye reef"},
          {"ff3 swim", FF3_SWIM_HUNDO, "superswim to forsaken fortress 3 from six eye reef"},
          {"puppet ganon skip", PUPPET_GANON_HUNDO, "skip, or fight puppet ganon"},
          {"ganondorf", GANONDORF_HUNDO, "ganondorf boss fight"}} {}

HundoSavesMenu::~HundoSavesMenu() {}

void HundoSavesMenu::draw() {
    if (GZ_getButtonTrig(BACK_BUTTON)) {
        g_menuMgr->pop();
        return;
    }

    special HundoSpecials[] = {
        special(MAILGAME_HUNDO, SaveMngSpecial_MailGame_Hundo),
        special(DRC_BK_SKIP_HUNDO, SaveMngSpecial_DRC_BK_Skip_Hundo),
        special(POTPUSH_STORAGE_HUNDO, SaveMngSpecial_DRCChestStorage_PMG),
        special(DRI_TO_WINDFALL_SWIM_HUNDO, SaveMngSpecial_WindfallSwim_Hundo),
        special(WINDFALL_TO_FH_HUNDO, SaveMngSpecial_WindfallToFHSwim_Hundo),
        special(DTCS_HUNDO, SaveMngSpecial_DTCS_Hundo),
        special(LEAF_TO_FOF_HUNDO, SaveMngSpecial_LeafToFoF_Hundo),
        special(FOF_FAIRY_CLIP_HUNDO, SaveMngSpecial_RollClipLeafGreatFairyFoF_Hundo),
        special(LEAF_TO_SHIP_HUNDO, SaveMngSpecial_LeafToInvisPirateShip_Hundo),
        special(FW_SKS_HUNDO, SaveMngSpecial_GiveChestStorage),
        special(OUTSET_TO_STI_HUNDO, SaveMngSpecial_EnterTotg_Hundo),
        special(HELMAROC_CS_SKIP_HUNDO, SaveMngSpecial_FF2HelmCSSkip_Hundo),
        special(ET_SONG_STONE_SKIP_HUNDO, SaveMngSpecial_GiveChestStorage),
        special(ET_FLOORMASTERS_HUNDO, SaveMngSpecial_ETFloormastersRoom_Hundo),
        special(ET_MIRROR_ROOM_HUNDO, SaveMngSpecial_GiveChestStorage),
        special(NEEDLE_TO_5EYE_SWIM_HUNDO, SaveMngSpecial_BushStorageNeedleRock_Hundo),
        special(FIVE_EYE_TO_ETI_SWIM_HUNDO, SaveMngSpecial_ChestStorageFiveEyeReef_Hundo),
        special(WIND_TEMPLE_LOCKED_ROOM_HUNDO, SaveMngSpecial_WindTempleLockedRoom_Hundo),
        special(STONEWATCHER_TO_6EYE_SWIM_HUNDO, SaveMngSpecial_6EyeSwim_Hundo),
        special(WIND_TEMPLE_LOCKED_ROOM_HUNDO, SaveMngSpecial_GiveChestStorage),
        special(TINGLE_TO_STONEWATCHER_SWIM_HUNDO, SaveMngSpecial_TingleIslandStorage_Hundo),
        special(CYCLOPS_TO_PAWPRINT_SWIM_HUNDO, SaveMngSpecial_PawprintSwim_Hundo),
        special(ORCA500_HUNDO, SaveMngSpecial_Orca500_Hundo),
        special(HEADSTONE_SUB_HUNDO, SaveMngSpecial_HeadstoneSubSwim),
        special(WESTERN_FAIRY_SWIM_HUNDO, SaveMngSpecial_FourEyeStorageOnChest_Hundo),
        special(CABANA_SWIM_HUNDO, SaveMngSpecial_FHStorageOnChestCabanaSwim_Hundo),
        special(GALE_SWIM_3_HUNDO, SaveMngSpecial_TingleIslandStorage_Hundo),
        special(FIVE_STAR_SWIM_HUNDO, SaveMngSpecial_TwoEyeTo5Star_Hundo),
        special(THORNED_FAIRY_SWIM_HUNDO, SaveMngSpecial_CliffPlateauToThornedFairy_Hundo),
        special(FF3_SWIM_HUNDO, SaveMngSpecial_FF3Swim_Hundo),
    };

    if (GZ_getButtonTrig(SELECTION_BUTTON)) {
        SaveManager::triggerLoad(cursor.y, "hundo", HundoSpecials, sizeof(HundoSpecials) / sizeof(HundoSpecials[0]));
        g_menuMgr->hide();
    }

    cursor.move(0, sizeof(lines) / sizeof(lines[0]));
    GZ_drawMenuLines(lines, cursor.y, sizeof(lines) / sizeof(lines[0]));
}